[project]
name = 'Decentralized-Intellectual-Property-Licensing-for-Music'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.licensing-terms]
path = 'contracts/licensing-terms.clar'
clarity_version = 2
epoch = 2.5

[contracts.royalty-distribution]
path = 'contracts/royalty-distribution.clar'
clarity_version = 2
epoch = 2.5

[contracts.song-registration]
path = 'contracts/song-registration.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
